[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.9.5"


[[constraint]]
  name = "github.com/pkg/errors"
  version = "v0.8.1"

[prune]
  go-tests = true
  unused-packages = true
